import type { Metadata } from "next";
// import { Bricolage_Grotesque } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./_components/Footer";

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const grot = Bricolage_Grotesque({
//   variable: "--font-grot",
//   subsets: ["latin"],
//   axes: ["opsz"],
// });

const grot = localFont({
  src: "./fonts/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf",
  variable: "--font-grot",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grot.variable} font-grot text-base px-3 min-h-screen relative flex flex-col antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
